import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shered/navbar";
import WorkoutProvider from "@/context/workoutProvide";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/shered/footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fit Log",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-black">

       <WorkoutProvider>
         <Navbar></Navbar>

        <div>
          {children}
        </div>
        <Footer></Footer>
       </WorkoutProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
